import type { NextPage } from "next";
import Head from "next/head";
import { HiOutlineCollection } from "react-icons/hi";
import DashboardModule from "../modules/dashboard";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Welcome!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DashboardModule />
    </>
  );
};

export default Home;
