import type { NextPage } from "next";
import Head from "next/head";
import SettingsModule from "../modules/settings";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Welcome!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SettingsModule />
    </>
  );
};

export default Home;
