import type { NextPage } from "next";
import Head from "next/head";
import TrendingModule from "../modules/trending";

const Trending: NextPage = () => {
  return (
    <>
      <Head>
        <title>Welcome!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TrendingModule />
    </>
  );
};

export default Trending;
